# Generated by Django 4.2.4 on 2023-08-22 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anony', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theory_feedback',
            name='Q2',
        ),
        migrations.RemoveField(
            model_name='theory_feedback',
            name='Q3',
        ),
        migrations.RemoveField(
            model_name='theory_feedback',
            name='Q4',
        ),
        migrations.RemoveField(
            model_name='theory_feedback',
            name='Q5',
        ),
        migrations.RemoveField(
            model_name='theory_feedback',
            name='Q6',
        ),
        migrations.RemoveField(
            model_name='theory_feedback',
            name='Q7',
        ),
        migrations.RemoveField(
            model_name='theory_feedback',
            name='Q8',
        ),
    ]
