# Generated by Django 4.2.4 on 2023-09-02 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anony', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practical_feedback',
            name='f_date',
            field=models.IntegerField(default=2023),
        ),
        migrations.AlterField(
            model_name='theory_feedback',
            name='f_date',
            field=models.IntegerField(default=2023),
        ),
    ]
