# Generated by Django 4.2.4 on 2023-09-17 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operat', '0001_initial'),
        ('anony', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='theory_feedback',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operat.faculty'),
        ),
        migrations.AddField(
            model_name='theory_feedback',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operat.subjects'),
        ),
        migrations.AddField(
            model_name='theory_feedback',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='anony.user'),
        ),
        migrations.AddField(
            model_name='practical_feedback',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operat.faculty'),
        ),
        migrations.AddField(
            model_name='practical_feedback',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operat.subjects'),
        ),
        migrations.AddField(
            model_name='practical_feedback',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='anony.user'),
        ),
    ]
