# Generated by Django 4.2.4 on 2023-08-25 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anony', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='practical_feedback',
            name='Q1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='practical_feedback',
            name='Q2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='practical_feedback',
            name='Q3',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='practical_feedback',
            name='Q4',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='practical_feedback',
            name='Q5',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='practical_feedback',
            name='Q6',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='practical_feedback',
            name='Q7',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='practical_feedback',
            name='Q8',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='theory_feedback',
            name='Q1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='theory_feedback',
            name='Q10',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='theory_feedback',
            name='Q11',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='theory_feedback',
            name='Q12',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='theory_feedback',
            name='Q2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='theory_feedback',
            name='Q3',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='theory_feedback',
            name='Q4',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='theory_feedback',
            name='Q5',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='theory_feedback',
            name='Q6',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='theory_feedback',
            name='Q7',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='theory_feedback',
            name='Q8',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='theory_feedback',
            name='Q9',
            field=models.IntegerField(null=True),
        ),
    ]
