# Generated by Django 4.2.4 on 2023-08-29 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anony', '0002_practical_feedback_q1_practical_feedback_q2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=35)),
                ('password', models.CharField(max_length=300)),
            ],
        ),
    ]
