# Generated by Django 4.2.4 on 2023-09-17 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anony', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practical_feedback',
            name='f_date',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='practical_feedback',
            name='faculty',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='practical_feedback',
            name='subject',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='practical_feedback',
            name='user',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='theory_feedback',
            name='f_date',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='theory_feedback',
            name='faculty',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='theory_feedback',
            name='subject',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='theory_feedback',
            name='user',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
