# Generated by Django 4.2.4 on 2023-08-29 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anony', '0003_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='practical_feedback',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='anony.user'),
        ),
        migrations.AddField(
            model_name='theory_feedback',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='anony.user'),
        ),
    ]
