# Generated by Django 4.2.4 on 2023-08-22 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Mapfaculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem', models.IntegerField()),
                ('faculty', models.CharField(max_length=200)),
                ('Semester', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
                ('divison', models.CharField(max_length=200)),
                ('theory', models.IntegerField(default=0)),
                ('practical', models.IntegerField(default=0)),
                ('tutorial', models.IntegerField()),
                ('practical_batch', models.IntegerField()),
                ('tutorial_batch', models.IntegerField()),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='subjects',
            name='semester',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='subject',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
