# Generated by Django 4.2.4 on 2023-09-06 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operat', '0002_alter_mapfaculty_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calculatedtheory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=200)),
                ('division', models.CharField(max_length=5)),
                ('batch', models.IntegerField()),
                ('semester', models.IntegerField()),
                ('f_date', models.IntegerField(default=2023)),
                ('Q1', models.IntegerField(null=True)),
                ('Q2', models.IntegerField(null=True)),
                ('Q3', models.IntegerField(null=True)),
                ('Q4', models.IntegerField(null=True)),
                ('Q5', models.IntegerField(null=True)),
                ('Q6', models.IntegerField(null=True)),
                ('Q7', models.IntegerField(null=True)),
                ('Q8', models.IntegerField(null=True)),
                ('Q9', models.IntegerField(null=True)),
                ('Q10', models.IntegerField(null=True)),
                ('Q11', models.IntegerField(null=True)),
                ('Q12', models.IntegerField(null=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operat.faculty')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operat.subjects')),
            ],
        ),
    ]
