# Generated by Django 4.2.4 on 2023-09-20 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operat', '0002_alter_mapfaculty_sem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapfaculty',
            name='practical_batch',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='mapfaculty',
            name='tutorial',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='mapfaculty',
            name='tutorial_batch',
            field=models.IntegerField(null=True),
        ),
    ]
