# Generated by Django 4.2.4 on 2023-09-18 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operat', '0002_subjects_faculty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='faculty',
        ),
        migrations.AddField(
            model_name='subjects',
            name='department',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
