# Generated by Django 4.2.4 on 2023-08-22 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operat', '0002_faculty_mapfaculty_subjects_semester_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapfaculty',
            name='Semester',
        ),
    ]
