# Generated by Django 4.2.4 on 2023-08-22 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operat', '0003_remove_mapfaculty_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapfaculty',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operat.faculty'),
        ),
        migrations.AlterField(
            model_name='mapfaculty',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operat.subjects'),
        ),
    ]
