# Generated by Django 4.2.4 on 2023-09-19 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operat', '0004_division'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapfaculty',
            name='divison',
        ),
        migrations.AddField(
            model_name='mapfaculty',
            name='division',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='operat.division'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='faculty',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operat.department'),
        ),
        migrations.AlterField(
            model_name='mapfaculty',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operat.department'),
        ),
        migrations.AlterField(
            model_name='mapfaculty',
            name='year',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='operat.department'),
            preserve_default=False,
        ),
    ]
