# Generated by Django 4.2.4 on 2023-08-22 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operat', '0004_alter_mapfaculty_faculty_alter_mapfaculty_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='questions',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=500)),
                ('option1', models.CharField(max_length=200)),
                ('option2', models.CharField(max_length=200)),
                ('option3', models.CharField(max_length=200)),
                ('option4', models.CharField(max_length=200)),
            ],
        ),
    ]
