# Generated by Django 4.2.4 on 2023-09-17 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operat', '0005_appuser_is_staff_alter_appuser_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
