# Generated by Django 4.2.4 on 2023-08-22 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operat', '0006_alter_questions_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='theory_questions',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('option1', models.CharField(max_length=200)),
                ('option2', models.CharField(max_length=200)),
                ('option3', models.CharField(max_length=200)),
                ('option4', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameModel(
            old_name='questions',
            new_name='practical_questions',
        ),
    ]
