# Generated by Django 4.2.4 on 2023-08-22 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operat', '0007_theory_questions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='calculate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
