# Generated by Django 4.2.4 on 2023-08-22 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operat', '0008_calculate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='calculate',
        ),
    ]
